baseurl = "https://smakarau.me"
title = "Siarhei Makarau"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<span>DevOps Engineer</span><span>Gamer</span><span>Music lover</span><span>Traveler</span><span>Geek</span>'
  logoimage = "images/photo.jpg"
  copyright = "Siarhei Makarau"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:siarhei.makarau@gmail.com"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/SM616"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/siarheimakarau"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/siarhei.makarau"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/siarhei_makarau"
